import type {
  ResilienceDimensionDefinition,
  ResilienceDimensionId,
  ResilienceSourceDescriptor,
  ResilienceStressScenario,
} from './types';

export interface ResilienceCountrySeedProfile {
  code: string;
  name: string;
  region: string;
  peerGroup: string;
  aliases: string[];
  neighbors: string[];
  strategicPartners: string[];
  seedDimensions: Record<ResilienceDimensionId, number>;
}

function isoDate(monthOffset = 0): string {
  const date = new Date(Date.UTC(2026, 2 - monthOffset, 16, 8, 0, 0));
  return date.toISOString();
}

export const RESILIENCE_BASELINE_COUNTRY_CODES = [
  'IR',
  'IL',
  'US',
  'IQ',
  'TR',
  'AM',
  'AZ',
  'TM',
  'AF',
  'PK',
  'RU',
  'CN',
  'BR',
  'IN',
  'JP',
] as const;

export const RESILIENCE_DIMENSIONS: ResilienceDimensionDefinition[] = [
  {
    id: 'macroFiscal',
    label: 'تاب‌آوری کلان‌اقتصادی و مالیه عمومی',
    shortLabel: 'کلان/مالی',
    description: 'فضای سیاستی بودجه، ضربه‌گیرهای مالی و ظرفیت جذب شوک در سطح دولت.',
    methodology: 'وزن این بعد بر پایه ظرفیت مالی دولت، انعطاف بودجه‌ای و توان تثبیت ضدچرخه‌ای محاسبه می‌شود.',
    weight: 0.09,
    chartGroup: 'economic',
  },
  {
    id: 'currencyExternal',
    label: 'تاب‌آوری ارزی و تراز خارجی',
    shortLabel: 'ارز/خارجی',
    description: 'توان مدیریت فشار ارزی، ذخایر خارجی و آسیب‌پذیری تامین مالی بیرونی.',
    methodology: 'این بعد نشان می‌دهد شوک ارزی یا تامین مالی خارجی با چه شدت و دامنه‌ای جذب می‌شود.',
    weight: 0.07,
    chartGroup: 'economic',
  },
  {
    id: 'tradeSanctions',
    label: 'تاب‌آوری تجاری و تحریمی',
    shortLabel: 'تجارت/تحریم',
    description: 'توان بازآرایی مسیرهای تجارت، بیمه، پرداخت و دورزدن گلوگاه‌های قانونی/بازاری.',
    methodology: 'نمره این بعد از تنوع مسیرهای تجاری، انعطاف زنجیره پرداخت و فشارهای خارجی تنظیم می‌شود.',
    weight: 0.08,
    chartGroup: 'economic',
  },
  {
    id: 'energy',
    label: 'تاب‌آوری انرژی',
    shortLabel: 'انرژی',
    description: 'تاب‌آوری تولید، توزیع و دسترسی انرژی در برابر اختلال داخلی و خارجی.',
    methodology: 'این بعد ترکیبی از تنوع منابع، انعطاف شبکه و اثرپذیری از گلوگاه‌های منطقه‌ای است.',
    weight: 0.07,
    chartGroup: 'infrastructure',
  },
  {
    id: 'foodWater',
    label: 'تاب‌آوری غذا و آب',
    shortLabel: 'غذا/آب',
    description: 'پایداری تامین غذا، آب و نهاده‌های پایه زیر فشار اقلیمی یا لجستیکی.',
    methodology: 'نمره بر اساس خوداتکایی نسبی، فشار اقلیمی و حساسیت زنجیره تامین غذا/آب تنظیم می‌شود.',
    weight: 0.07,
    chartGroup: 'societal',
  },
  {
    id: 'infrastructure',
    label: 'تاب‌آوری زیرساخت',
    shortLabel: 'زیرساخت',
    description: 'پایداری شبکه‌های حیاتی شامل برق، ارتباطات و تاسیسات پایه.',
    methodology: 'ترکیب پایداری شبکه، افزونگی و شدت اختلال‌های مشاهده‌شده در زیرساخت‌های حیاتی.',
    weight: 0.08,
    chartGroup: 'infrastructure',
  },
  {
    id: 'logisticsSupply',
    label: 'تاب‌آوری لجستیک و زنجیره تامین',
    shortLabel: 'لجستیک',
    description: 'توان حفظ جریان کالا، حمل‌ونقل و دسترسی به گلوگاه‌های حمل‌ونقل.',
    methodology: 'این بعد از کیفیت کریدورها، اختلال‌های هوایی/دریایی و انعطاف لجستیکی مشتق می‌شود.',
    weight: 0.08,
    chartGroup: 'infrastructure',
  },
  {
    id: 'socialCohesion',
    label: 'تاب‌آوری انسجام اجتماعی',
    shortLabel: 'اجتماعی',
    description: 'ظرفیت جامعه برای جذب فشار، جلوگیری از شکاف‌های شدید و بازیابی همبستگی.',
    methodology: 'این بعد از نارضایتی، جابجایی جمعیت و نشانه‌های تحمل اجتماعی تنظیم می‌شود.',
    weight: 0.08,
    chartGroup: 'societal',
  },
  {
    id: 'governanceInstitutional',
    label: 'تاب‌آوری حکمرانی و نهادی',
    shortLabel: 'حکمرانی',
    description: 'کارایی نهادی، هماهنگی تصمیم‌سازی و ظرفیت اجرای سیاست.',
    methodology: 'نمره این بعد بر مبنای ظرفیت هماهنگی و افت عملکرد تحت فشارهای مرکب تنظیم می‌شود.',
    weight: 0.08,
    chartGroup: 'governance',
  },
  {
    id: 'informationCognitive',
    label: 'تاب‌آوری اطلاعاتی و شناختی',
    shortLabel: 'اطلاعات/شناختی',
    description: 'توان مقابله با آشفتگی اطلاعاتی، شوک روایی و فرسایش اعتماد.',
    methodology: 'ترکیبی از کیفیت میدان اطلاعاتی، شدت اختلالات اطلاعاتی و آسیب‌پذیری روایی.',
    weight: 0.06,
    chartGroup: 'governance',
  },
  {
    id: 'cyberDigital',
    label: 'تاب‌آوری سایبری و دیجیتال',
    shortLabel: 'سایبری',
    description: 'پایداری سامانه‌های دیجیتال و توان تداوم خدمات تحت فشار سایبری.',
    methodology: 'این بعد از شدت تهدیدات سایبری، جمینگ، اختلالات شبکه و ظرفیت ادامه خدمت تنظیم می‌شود.',
    weight: 0.06,
    chartGroup: 'infrastructure',
  },
  {
    id: 'healthPublicService',
    label: 'تاب‌آوری سلامت و خدمات عمومی',
    shortLabel: 'سلامت/خدمت',
    description: 'توان حفظ خدمات درمانی و خدمات عمومی در برابر فشارهای امنیتی یا اقلیمی.',
    methodology: 'این بعد ظرفیت خدمات، فشار جابجایی و اثر اختلال زیرساختی بر خدمات عمومی را ترکیب می‌کند.',
    weight: 0.07,
    chartGroup: 'societal',
  },
  {
    id: 'environmentalClimate',
    label: 'تاب‌آوری محیط‌زیستی و اقلیمی',
    shortLabel: 'محیط‌زیست',
    description: 'توان جذب فشارهای اقلیمی، آتش‌سوزی، خشکسالی و شوک‌های محیطی.',
    methodology: 'این بعد اثرپذیری از تنش‌های اقلیمی و ظرفیت جذب شوک‌های محیط‌زیستی را ترکیب می‌کند.',
    weight: 0.05,
    chartGroup: 'societal',
  },
  {
    id: 'borderSecurity',
    label: 'تاب‌آوری مرزی و امنیتی',
    shortLabel: 'مرز/امنیت',
    description: 'توان مدیریت فشارهای مرزی، ناامنی پیرامونی و اختلال امنیتی در پیرامون کشور.',
    methodology: 'این بعد شدت فشار مرزی، همجواری بحران و توان مهار سرریز ناامنی را بازتاب می‌دهد.',
    weight: 0.06,
    chartGroup: 'security',
  },
];

export const RESILIENCE_METHOD_SOURCE: ResilienceSourceDescriptor = {
  id: 'resilience-method-2026q1',
  title: 'چارچوب شفاف تاب‌آوری QADR110 (نسخه 2026-03-16)',
  kind: 'public-indicator',
  synthetic: false,
  coverageNote: 'تعریف ابعاد، وزن‌ها و قواعد شفاف امتیازدهی.',
  lastUpdated: isoDate(),
  license: 'AGPL-3.0-only',
};

export const SAMPLE_BASELINE_SOURCE: ResilienceSourceDescriptor = {
  id: 'resilience-sample-baseline-2026q1',
  title: 'داده نمونه پایه برای مقایسه تاب‌آوری',
  kind: 'sample',
  synthetic: true,
  coverageNote: 'مقادیر این منبع نمونه/ترکیبی هستند و جایگزین داده ثبتی رسمی نیستند.',
  lastUpdated: isoDate(),
  license: 'Internal seeded demo dataset',
};

export const INTERNAL_SIGNAL_SOURCE: ResilienceSourceDescriptor = {
  id: 'resilience-internal-signals',
  title: 'سیگنال‌های نرمال‌شده داخلی QADR110',
  kind: 'internal-signal',
  synthetic: false,
  coverageNote: 'از سیگنال‌های داخلی مانند CII، اعتراضات، اختلالات، تهدیدات سایبری و داده‌های پروازی/دریایی استفاده می‌کند.',
  lastUpdated: isoDate(),
  license: 'Derived from configured public feeds inside QADR110',
};

export const RESILIENCE_STRESS_SCENARIOS: ResilienceStressScenario[] = [
  {
    id: 'sanctions-shock',
    title: 'شوک تحریمی و مالی',
    description: 'فشار همزمان بر تجارت، پرداخت، بیمه و دسترسی ارزی.',
    timeHorizon: '۳۰ تا ۹۰ روز',
    stressByDimension: {
      macroFiscal: 10,
      currencyExternal: 16,
      tradeSanctions: 18,
      logisticsSupply: 8,
      informationCognitive: 6,
    },
    monitoringSignals: ['اختلال بیمه/حمل', 'افزایش هشدارهای تجاری', 'فشار ارزی و لجستیکی'],
  },
  {
    id: 'border-escalation',
    title: 'تشدید مرزی و سرریز امنیتی',
    description: 'افزایش ناامنی پیرامونی، بستن گذرگاه‌ها و فرسایش جریان منطقه‌ای.',
    timeHorizon: '۷ تا ۳۰ روز',
    stressByDimension: {
      borderSecurity: 18,
      logisticsSupply: 12,
      socialCohesion: 8,
      energy: 7,
      infrastructure: 6,
    },
    monitoringSignals: ['افزایش درگیری پیرامونی', 'جابجایی جمعیت', 'اختلال کریدورهای زمینی'],
  },
  {
    id: 'energy-chokepoint',
    title: 'اختلال انرژی و گلوگاه حمل',
    description: 'اختلال در تاسیسات انرژی، بنادر، تنگه‌ها یا کریدورهای دریایی.',
    timeHorizon: '۳ تا ۲۱ روز',
    stressByDimension: {
      energy: 16,
      logisticsSupply: 14,
      macroFiscal: 8,
      tradeSanctions: 7,
      infrastructure: 8,
    },
    monitoringSignals: ['اختلال بندری', 'پرش ریسک حمل', 'وقفه در عرضه یا صادرات انرژی'],
  },
  {
    id: 'climate-water-stress',
    title: 'فشار اقلیمی و تنش آب/غذا',
    description: 'شوک همزمان بر منابع آب، کشاورزی، سلامت و جابجایی جمعیت.',
    timeHorizon: '۱ تا ۶ ماه',
    stressByDimension: {
      foodWater: 16,
      environmentalClimate: 18,
      healthPublicService: 10,
      socialCohesion: 8,
      logisticsSupply: 6,
    },
    monitoringSignals: ['افزایش تنش اقلیمی', 'آتش‌سوزی/خشکسالی', 'فشار بر خدمات عمومی'],
  },
];

export const RESILIENCE_COUNTRY_SEEDS: Record<string, ResilienceCountrySeedProfile> = {
  IR: {
    code: 'IR',
    name: 'ایران',
    region: 'خاورمیانه',
    peerGroup: 'قدرت منطقه‌ای در فشار تحریم',
    aliases: ['Iran', 'Islamic Republic of Iran'],
    neighbors: ['IQ', 'TR', 'AM', 'AZ', 'TM', 'AF', 'PK'],
    strategicPartners: ['RU', 'CN', 'IN'],
    seedDimensions: {
      macroFiscal: 50,
      currencyExternal: 35,
      tradeSanctions: 55,
      energy: 75,
      foodWater: 40,
      infrastructure: 50,
      logisticsSupply: 45,
      socialCohesion: 45,
      governanceInstitutional: 50,
      informationCognitive: 55,
      cyberDigital: 45,
      healthPublicService: 50,
      environmentalClimate: 35,
      borderSecurity: 40,
    },
  },
  IL: {
    code: 'IL',
    name: 'اسرائیل',
    region: 'خاورمیانه',
    peerGroup: 'اقتصاد پیشرفته با فشار امنیتی',
    aliases: ['Israel'],
    neighbors: ['TR', 'US'],
    strategicPartners: ['US', 'JP'],
    seedDimensions: {
      macroFiscal: 70,
      currencyExternal: 75,
      tradeSanctions: 70,
      energy: 65,
      foodWater: 60,
      infrastructure: 68,
      logisticsSupply: 62,
      socialCohesion: 45,
      governanceInstitutional: 68,
      informationCognitive: 52,
      cyberDigital: 72,
      healthPublicService: 74,
      environmentalClimate: 48,
      borderSecurity: 38,
    },
  },
  US: {
    code: 'US',
    name: 'ایالات متحده',
    region: 'آمریکای شمالی',
    peerGroup: 'اقتصاد بزرگ جهانی',
    aliases: ['United States', 'USA'],
    neighbors: ['JP', 'BR'],
    strategicPartners: ['IL', 'JP', 'IN', 'TR'],
    seedDimensions: {
      macroFiscal: 78,
      currencyExternal: 80,
      tradeSanctions: 82,
      energy: 78,
      foodWater: 75,
      infrastructure: 65,
      logisticsSupply: 82,
      socialCohesion: 55,
      governanceInstitutional: 68,
      informationCognitive: 55,
      cyberDigital: 76,
      healthPublicService: 68,
      environmentalClimate: 52,
      borderSecurity: 72,
    },
  },
  IQ: {
    code: 'IQ',
    name: 'عراق',
    region: 'خاورمیانه',
    peerGroup: 'همسایه در معرض سرریز امنیتی',
    aliases: ['Iraq'],
    neighbors: ['IR', 'TR'],
    strategicPartners: ['US', 'TR'],
    seedDimensions: {
      macroFiscal: 35,
      currencyExternal: 35,
      tradeSanctions: 40,
      energy: 55,
      foodWater: 35,
      infrastructure: 32,
      logisticsSupply: 34,
      socialCohesion: 30,
      governanceInstitutional: 28,
      informationCognitive: 32,
      cyberDigital: 28,
      healthPublicService: 32,
      environmentalClimate: 30,
      borderSecurity: 25,
    },
  },
  TR: {
    code: 'TR',
    name: 'ترکیه',
    region: 'خاورمیانه/اوراسیا',
    peerGroup: 'قدرت منطقه‌ای چندکریدوری',
    aliases: ['Turkey', 'Türkiye'],
    neighbors: ['IR', 'IQ', 'AM', 'AZ'],
    strategicPartners: ['US', 'RU', 'CN'],
    seedDimensions: {
      macroFiscal: 55,
      currencyExternal: 45,
      tradeSanctions: 60,
      energy: 55,
      foodWater: 52,
      infrastructure: 62,
      logisticsSupply: 70,
      socialCohesion: 48,
      governanceInstitutional: 52,
      informationCognitive: 46,
      cyberDigital: 58,
      healthPublicService: 60,
      environmentalClimate: 45,
      borderSecurity: 50,
    },
  },
  AM: {
    code: 'AM',
    name: 'ارمنستان',
    region: 'قفقاز جنوبی',
    peerGroup: 'دولت کوچک در گره ژئوپلیتیک',
    aliases: ['Armenia'],
    neighbors: ['IR', 'TR', 'AZ'],
    strategicPartners: ['RU'],
    seedDimensions: {
      macroFiscal: 45,
      currencyExternal: 45,
      tradeSanctions: 42,
      energy: 42,
      foodWater: 50,
      infrastructure: 45,
      logisticsSupply: 38,
      socialCohesion: 48,
      governanceInstitutional: 46,
      informationCognitive: 44,
      cyberDigital: 42,
      healthPublicService: 50,
      environmentalClimate: 44,
      borderSecurity: 35,
    },
  },
  AZ: {
    code: 'AZ',
    name: 'آذربایجان',
    region: 'قفقاز جنوبی',
    peerGroup: 'صادرکننده انرژی در کریدور منطقه‌ای',
    aliases: ['Azerbaijan'],
    neighbors: ['IR', 'TR', 'AM', 'RU'],
    strategicPartners: ['TR', 'IL'],
    seedDimensions: {
      macroFiscal: 50,
      currencyExternal: 52,
      tradeSanctions: 48,
      energy: 68,
      foodWater: 48,
      infrastructure: 52,
      logisticsSupply: 55,
      socialCohesion: 45,
      governanceInstitutional: 45,
      informationCognitive: 42,
      cyberDigital: 48,
      healthPublicService: 46,
      environmentalClimate: 42,
      borderSecurity: 42,
    },
  },
  TM: {
    code: 'TM',
    name: 'ترکمنستان',
    region: 'آسیای مرکزی',
    peerGroup: 'صادرکننده انرژی با اتصال محدود',
    aliases: ['Turkmenistan'],
    neighbors: ['IR', 'AF'],
    strategicPartners: ['CN', 'RU'],
    seedDimensions: {
      macroFiscal: 42,
      currencyExternal: 44,
      tradeSanctions: 40,
      energy: 65,
      foodWater: 38,
      infrastructure: 40,
      logisticsSupply: 36,
      socialCohesion: 42,
      governanceInstitutional: 36,
      informationCognitive: 38,
      cyberDigital: 34,
      healthPublicService: 40,
      environmentalClimate: 32,
      borderSecurity: 40,
    },
  },
  AF: {
    code: 'AF',
    name: 'افغانستان',
    region: 'آسیای جنوبی',
    peerGroup: 'همسایه با شکنندگی مزمن',
    aliases: ['Afghanistan'],
    neighbors: ['IR', 'TM', 'PK'],
    strategicPartners: ['PK', 'CN'],
    seedDimensions: {
      macroFiscal: 20,
      currencyExternal: 18,
      tradeSanctions: 22,
      energy: 18,
      foodWater: 18,
      infrastructure: 15,
      logisticsSupply: 18,
      socialCohesion: 20,
      governanceInstitutional: 15,
      informationCognitive: 20,
      cyberDigital: 12,
      healthPublicService: 15,
      environmentalClimate: 18,
      borderSecurity: 15,
    },
  },
  PK: {
    code: 'PK',
    name: 'پاکستان',
    region: 'آسیای جنوبی',
    peerGroup: 'قدرت منطقه‌ای با فشار مالی/امنیتی',
    aliases: ['Pakistan'],
    neighbors: ['IR', 'AF', 'IN', 'CN'],
    strategicPartners: ['CN', 'TR'],
    seedDimensions: {
      macroFiscal: 32,
      currencyExternal: 28,
      tradeSanctions: 38,
      energy: 35,
      foodWater: 34,
      infrastructure: 36,
      logisticsSupply: 42,
      socialCohesion: 30,
      governanceInstitutional: 28,
      informationCognitive: 32,
      cyberDigital: 34,
      healthPublicService: 30,
      environmentalClimate: 28,
      borderSecurity: 32,
    },
  },
  RU: {
    code: 'RU',
    name: 'روسیه',
    region: 'اوراسیا',
    peerGroup: 'قدرت بزرگ در فشار ژئوپلیتیک',
    aliases: ['Russia'],
    neighbors: ['AZ', 'CN', 'TR'],
    strategicPartners: ['IR', 'CN', 'IN'],
    seedDimensions: {
      macroFiscal: 60,
      currencyExternal: 58,
      tradeSanctions: 52,
      energy: 75,
      foodWater: 60,
      infrastructure: 58,
      logisticsSupply: 55,
      socialCohesion: 40,
      governanceInstitutional: 48,
      informationCognitive: 52,
      cyberDigital: 56,
      healthPublicService: 50,
      environmentalClimate: 42,
      borderSecurity: 45,
    },
  },
  CN: {
    code: 'CN',
    name: 'چین',
    region: 'آسیا-اقیانوسیه',
    peerGroup: 'اقتصاد بزرگ صنعتی',
    aliases: ['China'],
    neighbors: ['PK', 'IN', 'RU'],
    strategicPartners: ['IR', 'BR', 'RU'],
    seedDimensions: {
      macroFiscal: 72,
      currencyExternal: 75,
      tradeSanctions: 70,
      energy: 62,
      foodWater: 60,
      infrastructure: 80,
      logisticsSupply: 82,
      socialCohesion: 58,
      governanceInstitutional: 68,
      informationCognitive: 62,
      cyberDigital: 74,
      healthPublicService: 72,
      environmentalClimate: 45,
      borderSecurity: 64,
    },
  },
  BR: {
    code: 'BR',
    name: 'برزیل',
    region: 'آمریکای لاتین',
    peerGroup: 'اقتصاد بزرگ نوظهور',
    aliases: ['Brazil'],
    neighbors: ['US'],
    strategicPartners: ['CN', 'IN'],
    seedDimensions: {
      macroFiscal: 50,
      currencyExternal: 52,
      tradeSanctions: 58,
      energy: 72,
      foodWater: 68,
      infrastructure: 48,
      logisticsSupply: 55,
      socialCohesion: 45,
      governanceInstitutional: 42,
      informationCognitive: 44,
      cyberDigital: 50,
      healthPublicService: 52,
      environmentalClimate: 40,
      borderSecurity: 58,
    },
  },
  IN: {
    code: 'IN',
    name: 'هند',
    region: 'آسیای جنوبی',
    peerGroup: 'اقتصاد بزرگ در حال رشد',
    aliases: ['India'],
    neighbors: ['PK', 'CN'],
    strategicPartners: ['US', 'IR', 'JP'],
    seedDimensions: {
      macroFiscal: 55,
      currencyExternal: 50,
      tradeSanctions: 62,
      energy: 48,
      foodWater: 45,
      infrastructure: 58,
      logisticsSupply: 66,
      socialCohesion: 46,
      governanceInstitutional: 50,
      informationCognitive: 48,
      cyberDigital: 62,
      healthPublicService: 48,
      environmentalClimate: 36,
      borderSecurity: 52,
    },
  },
  JP: {
    code: 'JP',
    name: 'ژاپن',
    region: 'آسیا-اقیانوسیه',
    peerGroup: 'اقتصاد پیشرفته با ریسک طبیعی',
    aliases: ['Japan'],
    neighbors: ['US'],
    strategicPartners: ['US', 'IN'],
    seedDimensions: {
      macroFiscal: 68,
      currencyExternal: 82,
      tradeSanctions: 76,
      energy: 52,
      foodWater: 70,
      infrastructure: 82,
      logisticsSupply: 78,
      socialCohesion: 70,
      governanceInstitutional: 78,
      informationCognitive: 68,
      cyberDigital: 76,
      healthPublicService: 82,
      environmentalClimate: 50,
      borderSecurity: 70,
    },
  },
};

export const RESILIENCE_COUNTRY_NAME_MAP = Object.fromEntries(
  Object.values(RESILIENCE_COUNTRY_SEEDS).map((country) => [country.code, country.name]),
) as Record<string, string>;

export function getResilienceSeedCountry(code: string): ResilienceCountrySeedProfile | undefined {
  return RESILIENCE_COUNTRY_SEEDS[code.toUpperCase()];
}

export function getResilienceDimensionDefinition(id: ResilienceDimensionId): ResilienceDimensionDefinition {
  const definition = RESILIENCE_DIMENSIONS.find((item) => item.id === id);
  if (!definition) {
    throw new Error(`Unknown resilience dimension: ${id}`);
  }
  return definition;
}
