import type { CapabilityAdapterManifest } from './contracts';

export const DEFAULT_PLATFORM_ADAPTERS: CapabilityAdapterManifest[] = [
  {
    id: 'generic-structured-import',
    displayName: 'Structured Import Boundary',
    category: 'interoperability',
    vendorNeutralFamily: 'structured-data-import',
    runtimeFeatureFlags: [],
    requiredConfigKeys: [],
    interoperabilityTags: ['JSON', 'CSV', 'GeoJSON', 'XML'],
    openSource: true,
    licenseNotes: 'Portable import/export boundary using open formats and repository-native normalizers.',
    degradation: {
      mode: 'manual',
      message: 'If automatic import fails, the operator can still review and adapt the payload manually.',
    },
    capabilities: [
      {
        id: 'structured-import',
        kind: 'ingestion',
        name: 'Structured Import',
        description: 'Ingests JSON, CSV, GeoJSON, XML, STIX 2.1, and MISP-like payloads into canonical QADR110 records.',
        inputs: ['structuredPayload', 'format', 'sourceMetadata'],
        outputs: ['canonicalBundle'],
      },
      {
        id: 'structured-export',
        kind: 'report-generation',
        name: 'Portable Export',
        description: 'Exports canonical evidence bundles into portable formats for downstream analysis.',
        inputs: ['canonicalBundle'],
        outputs: ['portableDataset'],
        evidenceAware: true,
      },
    ],
  },
  {
    id: 'openrouter-gateway',
    displayName: 'OpenRouter AI Gateway',
    category: 'ai',
    vendorNeutralFamily: 'openai-compatible-router',
    runtimeFeatureFlags: ['aiOpenRouter'],
    requiredConfigKeys: ['OPENROUTER_API_KEY'],
    optionalConfigKeys: ['OPENROUTER_MODEL'],
    interoperabilityTags: ['OpenAI-compatible', 'JSON mode', 'streaming'],
    openSource: false,
    licenseNotes: 'Third-party hosted gateway; integration remains provider-neutral via OpenAI-compatible contracts.',
    degradation: {
      mode: 'manual',
      message: 'OpenRouter is not configured; QADR110 falls back to local/self-hosted or browser inference.',
    },
    capabilities: [
      {
        id: 'openrouter-chat',
        kind: 'scenario-analysis',
        name: 'Scenario Analysis',
        description: 'Multi-model strategic reasoning, scenario comparison, and narrative synthesis.',
        inputs: ['prompt', 'geoContext', 'evidenceBundle'],
        outputs: ['analysisMarkdown', 'traceMetadata'],
        evidenceAware: true,
        geoAware: true,
      },
      {
        id: 'openrouter-report',
        kind: 'report-generation',
        name: 'Report Generation',
        description: 'Explainable report drafting with evidence lineage and structured sections.',
        inputs: ['promptCatalogEntry', 'evidenceBundle', 'audienceProfile'],
        outputs: ['reportMarkdown', 'citations'],
        evidenceAware: true,
      },
    ],
  },
  {
    id: 'local-llm-hub',
    displayName: 'Local LLM Hub',
    category: 'ai',
    vendorNeutralFamily: 'self-hosted-openai-compatible',
    runtimeFeatureFlags: ['aiOllama'],
    requiredConfigKeys: ['OLLAMA_API_URL', 'OLLAMA_MODEL'],
    optionalConfigKeys: ['VLLM_API_URL', 'VLLM_API_KEY'],
    interoperabilityTags: ['Ollama', 'vLLM', 'LM Studio', 'air-gapped'],
    openSource: true,
    licenseNotes: 'Depends on the chosen local model license; contract remains vendor-neutral.',
    degradation: {
      mode: 'manual',
      message: 'Local inference is not configured; cloud or browser fallbacks remain available.',
    },
    capabilities: [
      {
        id: 'local-summary',
        kind: 'retrieval',
        name: 'Local Retrieval Summaries',
        description: 'On-device summarization and brief generation for sensitive workflows.',
        inputs: ['headlines', 'prompt', 'context'],
        outputs: ['summary', 'modelTrace'],
        evidenceAware: true,
      },
      {
        id: 'local-scenario',
        kind: 'scenario-analysis',
        name: 'Local Scenario Analysis',
        description: 'Self-hosted analysis route for disconnected or privacy-sensitive deployments.',
        inputs: ['scenarioPrompt', 'mapContext', 'evidenceBundle'],
        outputs: ['analysisMarkdown'],
        evidenceAware: true,
        geoAware: true,
      },
    ],
  },
  {
    id: 'osint-ingestion-hub',
    displayName: 'OSINT Ingestion Hub',
    category: 'osint',
    vendorNeutralFamily: 'rss-api-web-ingestion',
    runtimeFeatureFlags: [],
    requiredConfigKeys: [],
    optionalConfigKeys: ['TAVILY_API_KEYS', 'BRAVE_API_KEYS', 'SERPAPI_API_KEYS'],
    interoperabilityTags: ['RSS', 'APIs', 'public web'],
    openSource: true,
    licenseNotes: 'Uses source-specific terms; connectors must respect provider terms and robots/access controls.',
    degradation: {
      mode: 'cached',
      message: 'When premium search is unavailable, RSS/bootstrap caches continue to provide partial coverage.',
    },
    capabilities: [
      {
        id: 'osint-ingest',
        kind: 'ingestion',
        name: 'Source Ingestion',
        description: 'Ingests public feeds, curated APIs, and relay-backed sources into normalized records.',
        inputs: ['feedDefinition', 'pollWindow'],
        outputs: ['normalizedSourceRecords'],
      },
      {
        id: 'osint-search',
        kind: 'search',
        name: 'Targeted Search',
        description: 'Expands public-source collection with provider-specific search adapters.',
        inputs: ['query', 'filters'],
        outputs: ['searchHits'],
      },
    ],
  },
  {
    id: 'misp-stix-bridge',
    displayName: 'MISP / STIX Bridge',
    category: 'interoperability',
    vendorNeutralFamily: 'threat-intel-exchange',
    runtimeFeatureFlags: [],
    requiredConfigKeys: [],
    optionalConfigKeys: ['MISP_URL', 'MISP_API_KEY', 'URLHAUS_AUTH_KEY', 'OTX_API_KEY', 'ABUSEIPDB_API_KEY'],
    interoperabilityTags: ['MISP', 'STIX 2.1', 'TAXII', 'indicator exchange'],
    openSource: true,
    licenseNotes: 'QADR110 exposes a compatible bridge contract only; actual MISP/TAXII wiring remains opt-in.',
    degradation: {
      mode: 'readonly',
      message: 'Threat intel exchange is unavailable; local indicators remain visible without bidirectional sync.',
    },
    capabilities: [
      {
        id: 'misp-retrieval',
        kind: 'retrieval',
        name: 'Indicator Retrieval',
        description: 'Retrieves indicator bundles and attribute-level enrichment compatible with MISP/STIX workflows.',
        inputs: ['indicatorQuery', 'timeRange'],
        outputs: ['indicatorBundle'],
        evidenceAware: true,
      },
      {
        id: 'misp-correlation',
        kind: 'correlation',
        name: 'Indicator Correlation',
        description: 'Correlates cyber indicators with broader geopolitical and infrastructure signals.',
        inputs: ['indicatorBundle', 'eventGraph'],
        outputs: ['correlationFindings'],
        evidenceAware: true,
      },
    ],
  },
  {
    id: 'investigation-workbench',
    displayName: 'Investigation Workbench',
    category: 'investigation',
    vendorNeutralFamily: 'entity-link-analysis',
    runtimeFeatureFlags: [],
    requiredConfigKeys: [],
    interoperabilityTags: ['graph analysis', 'case management', 'entity resolution'],
    openSource: true,
    licenseNotes: 'Inspired by investigation workflows without claiming proprietary integration.',
    degradation: {
      mode: 'manual',
      message: 'Case-management connectors are absent; analysts can still export canonical entity/event graphs.',
    },
    capabilities: [
      {
        id: 'graph-correlation',
        kind: 'correlation',
        name: 'Graph Correlation',
        description: 'Links entities, events, indicators, and claims for investigative workflows.',
        inputs: ['entities', 'events', 'claims'],
        outputs: ['relationshipGraph'],
        evidenceAware: true,
      },
      {
        id: 'case-report',
        kind: 'report-generation',
        name: 'Case Report Drafting',
        description: 'Builds explainable case summaries with evidence references.',
        inputs: ['relationshipGraph', 'evidenceBundle'],
        outputs: ['caseSummary'],
        evidenceAware: true,
      },
    ],
  },
  {
    id: 'geospatial-workbench',
    displayName: 'Geospatial Workbench',
    category: 'geospatial',
    vendorNeutralFamily: 'map-layer-analytics',
    runtimeFeatureFlags: [],
    requiredConfigKeys: [],
    interoperabilityTags: ['GeoJSON', 'deck.gl', 'MapLibre', 'terrain workflows'],
    openSource: true,
    licenseNotes: 'Compatible with geospatial workflows; no proprietary SDK dependency implied.',
    degradation: {
      mode: 'readonly',
      message: 'Advanced geospatial enrichment is unavailable; core map layers remain operational.',
    },
    capabilities: [
      {
        id: 'geo-enrichment',
        kind: 'geospatial-enrichment',
        name: 'Geospatial Enrichment',
        description: 'Adds country, polygon, proximity, and layer context around analyst-selected geography.',
        inputs: ['point', 'polygon', 'selectedLayers'],
        outputs: ['geoContext'],
        geoAware: true,
      },
      {
        id: 'geo-scenario',
        kind: 'scenario-analysis',
        name: 'Geo Scenario Analysis',
        description: 'Evaluates scenario impacts against terrain, routes, infrastructure, and timeline context.',
        inputs: ['scenario', 'geoContext', 'eventGraph'],
        outputs: ['geoImpactAssessment'],
        evidenceAware: true,
        geoAware: true,
      },
    ],
  },
  {
    id: 'vector-store-bridge',
    displayName: 'Vector Retrieval Bridge',
    category: 'storage',
    vendorNeutralFamily: 'semantic-retrieval',
    runtimeFeatureFlags: [],
    requiredConfigKeys: [],
    optionalConfigKeys: ['WEAVIATE_URL', 'WEAVIATE_API_KEY', 'CHROMA_URL'],
    interoperabilityTags: ['Weaviate', 'Chroma', 'embeddings'],
    openSource: true,
    licenseNotes: 'Supports open-source vector stores and compatible hosted deployments via adapter contracts.',
    degradation: {
      mode: 'cached',
      message: 'Vector retrieval is unavailable; QADR110 falls back to lexical context and cached headline memory.',
    },
    capabilities: [
      {
        id: 'vector-retrieve',
        kind: 'vector-retrieval',
        name: 'Semantic Retrieval',
        description: 'Retrieves semantically similar records for memory-augmented briefs and prompts.',
        inputs: ['queryEmbedding', 'filters'],
        outputs: ['retrievalMatches'],
        evidenceAware: true,
      },
      {
        id: 'vector-search',
        kind: 'search',
        name: 'Semantic Search',
        description: 'Searches evidence and claims by meaning rather than exact term match.',
        inputs: ['queryText', 'scope'],
        outputs: ['semanticHits'],
        evidenceAware: true,
      },
    ],
  },
  {
    id: 'data-exchange-bridge',
    displayName: 'Analytics Lakehouse Exchange',
    category: 'interoperability',
    vendorNeutralFamily: 'warehouse-lakehouse-exchange',
    runtimeFeatureFlags: [],
    requiredConfigKeys: [],
    interoperabilityTags: ['Parquet', 'JSONL', 'Arrow', 'Databricks', 'Snowflake'],
    openSource: true,
    licenseNotes: 'Data exchange targets open formats; named platforms are compatibility goals, not native bundled integrations.',
    degradation: {
      mode: 'manual',
      message: 'Warehouse export/import is not configured; analysts can still export portable JSON bundles.',
    },
    capabilities: [
      {
        id: 'lakehouse-retrieval',
        kind: 'retrieval',
        name: 'Batch Retrieval',
        description: 'Loads fact tables, event batches, and enrichment snapshots from external analytics stores.',
        inputs: ['datasetRef', 'timeWindow'],
        outputs: ['batchRecords'],
      },
      {
        id: 'lakehouse-report',
        kind: 'report-generation',
        name: 'Analytic Export',
        description: 'Exports canonical QADR110 entities/events/evidence into exchange-friendly formats.',
        inputs: ['graph', 'evidenceBundle'],
        outputs: ['exportManifest'],
        evidenceAware: true,
      },
    ],
  },
  {
    id: 'simulation-exchange',
    displayName: 'Scenario Simulation Exchange',
    category: 'interoperability',
    vendorNeutralFamily: 'simulation-event-exchange',
    runtimeFeatureFlags: [],
    requiredConfigKeys: [],
    interoperabilityTags: ['DIS', 'HLA-like exchange', 'event simulation'],
    openSource: true,
    licenseNotes: 'Provides event-exchange contracts for lawful defensive exercises only.',
    degradation: {
      mode: 'readonly',
      message: 'Simulation exchange is unavailable; scenario products remain descriptive and non-interactive.',
    },
    capabilities: [
      {
        id: 'simulation-scenario',
        kind: 'scenario-analysis',
        name: 'Scenario Exchange',
        description: 'Packages scenario assumptions, time windows, and defensive outcomes for external simulators.',
        inputs: ['scenario', 'resilienceScores'],
        outputs: ['simulationEnvelope'],
        geoAware: true,
      },
    ],
  },
  {
    id: 'edge-resilience-node',
    displayName: 'Edge Resilience Node',
    category: 'interoperability',
    vendorNeutralFamily: 'rugged-edge-deployment',
    runtimeFeatureFlags: ['aiOllama'],
    requiredConfigKeys: [],
    interoperabilityTags: ['offline mode', 'Tauri', 'portable bundles'],
    openSource: true,
    licenseNotes: 'Deployment pattern for disconnected or contested environments; no tactical guidance included.',
    degradation: {
      mode: 'cached',
      message: 'Edge node features are not enabled; the platform remains cloud-connected only.',
    },
    capabilities: [
      {
        id: 'edge-retrieval',
        kind: 'retrieval',
        name: 'Edge Snapshot Retrieval',
        description: 'Retrieves last-known-good evidence and model outputs in disconnected environments.',
        inputs: ['snapshotRef'],
        outputs: ['portableSnapshot'],
      },
      {
        id: 'edge-resilience',
        kind: 'resilience-scoring',
        name: 'Edge Resilience Scoring',
        description: 'Calculates resilience under degraded comms, data, and compute availability.',
        inputs: ['scenario', 'deploymentProfile'],
        outputs: ['resilienceAssessment'],
        evidenceAware: true,
      },
    ],
  },
  {
    id: 'workforce-intelligence-bridge',
    displayName: 'Workforce Intelligence Bridge',
    category: 'workforce',
    vendorNeutralFamily: 'personnel-readiness-operations',
    runtimeFeatureFlags: [],
    requiredConfigKeys: [],
    interoperabilityTags: ['personnel readiness', 'tasking', 'skills inventory'],
    openSource: true,
    licenseNotes: 'Supports defensive readiness and staffing workflows; excludes coercive or unlawful personnel targeting.',
    degradation: {
      mode: 'manual',
      message: 'Personnel/workforce connectors are not configured; readiness outputs remain advisory-only.',
    },
    capabilities: [
      {
        id: 'workforce-resilience',
        kind: 'resilience-scoring',
        name: 'Workforce Resilience',
        description: 'Scores analyst/team readiness, continuity, and coverage gaps for defensive operations.',
        inputs: ['teamRoster', 'skillsCoverage', 'shiftPlan'],
        outputs: ['readinessScore'],
      },
      {
        id: 'workforce-report',
        kind: 'report-generation',
        name: 'Workforce Reporting',
        description: 'Builds explainable readiness briefs tied to lawful defensive playbooks.',
        inputs: ['readinessScore', 'playbookRefs'],
        outputs: ['readinessBrief'],
      },
    ],
  },
  {
    id: 'palantir-compatibility',
    displayName: 'Palantir Compatibility Boundary',
    category: 'interoperability',
    vendorNeutralFamily: 'ontology-sdk-compatibility',
    runtimeFeatureFlags: [],
    requiredConfigKeys: [],
    optionalConfigKeys: ['PALANTIR_FOUNDRY_URL', 'PALANTIR_FOUNDRY_TOKEN', 'PYTHON_SIDECAR_URL'],
    interoperabilityTags: ['Foundry-like APIs', 'OSDK-inspired ontology mapping', 'Python bridge'],
    openSource: true,
    licenseNotes: 'Compatibility-only boundary; live integration requires real endpoints, credentials, and public/legal SDK paths.',
    degradation: {
      mode: 'manual',
      message: 'Without credentials/endpoints, QADR110 exposes export-ready ontology mappings only.',
    },
    capabilities: [
      {
        id: 'palantir-ontology-export',
        kind: 'report-generation',
        name: 'Ontology Compatibility Export',
        description: 'Projects canonical entities, events, and relationships into OSDK-inspired object mappings.',
        inputs: ['canonicalBundle'],
        outputs: ['ontologyCompatibilityEnvelope'],
        evidenceAware: true,
      },
      {
        id: 'palantir-python-bridge',
        kind: 'retrieval',
        name: 'Python Bridge Boundary',
        description: 'Declares an optional sidecar path for Python-first SDK workflows when configured.',
        inputs: ['bridgeEnvelope'],
        outputs: ['bridgeResponse'],
      },
    ],
  },
];
